# Generated by Django 6.0.2 on 2026-03-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_order_status_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_status',
            field=models.CharField(choices=[('none', 'No Request'), ('requested', 'Cancel Requested'), ('approved', 'Cancel Approved'), ('rejected', 'Cancel Rejected')], default='none', max_length=20),
        ),
    ]
