# Generated by Django 6.0.2 on 2026-03-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('placed', 'Order Placed'), ('accepted', 'Accepted'), ('progress', 'In Progress'), ('ontheway', 'On The Way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='placed', max_length=20),
        ),
    ]
