# Generated by Django 6.0.2 on 2026-03-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('lb', 'Pound'), ('oz', 'Ounce'), ('ml', 'Milliliter'), ('l', 'Liter')], default='kg', max_length=10),
        ),
    ]
