# Generated by Django 6.0.2 on 2026-03-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_weight_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_thumbnail',
            field=models.BooleanField(default=False, help_text='Main thumbnail image'),
        ),
    ]
