# Generated by Django 6.0.2 on 2026-03-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage_is_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
