# Generated by Django 6.0.2 on 2026-03-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number appears first'),
        ),
    ]
